apiVersion: v1
kind: Service
metadata:
  name: auntk-prj3-kub
spec:
  type: LoadBalancer
  selector:
    app: coworking
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auntk-prj3-kub
  labels:
    name: auntk-prj3-kub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking
  template:
    metadata:
      labels:
        app: coworking
    spec:
      containers:
      - name: coworking
        image: 145974184549.dkr.ecr.us-east-1.amazonaws.com/udacity/coworkers
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: db-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coworking
              key: DB_PASSWORD
      restartPolicy: Always